CREATE TABLE Schema
(schema_id NUMBER(10) PRIMARY KEY,
name VARCHAR2(50) NOT NULL);
 
CREATE TABLE ERObject
(object_id NUMBER(10) PRIMARY KEY,
x NUMBER(10),
y NUMBER(10),
width NUMBER(10),
height NUMBER(10),
name VARCHAR2(50) NOT NULL,
weak NUMBER(1),
o_type NUMBER(1),
schema_id NUMBE  R(10),
CONSTRAINT “SCHEMA_EROBJECT_FK” FOREIGN KEY(schema_id)
REFERENCES Schema (schema_id));


CREATE TABLE Entity
(entity_id NUMBER(10) PRIMARY KEY,
object_id NUMBER(10),
CONSTRAINT “EROBJECT_ENTITY_FK” FOREIGN KEY(object_id)
REFERENCES ERObject (object_id));


CREATE TABLE Attribute
(attribute_id NUMBER(10) PRIMARY KEY,
entity_id NUMBER(10),
name VARCHAR2(50) NOT NULL,
iskey NUMBER(1),
CONSTRAINT “ENTITY_ATTRIBUTE_FK” FOREIGN KEY(entity_id)
REFERENCES Entity (entity_id));


CREATE TABLE Relationship
(relationship_id NUMBER(10) PRIMARY KEY,
object_id NUMBER(10),
CONSTRAINT “EROBJECT_RELATIONSHIP_FK” FOREIGN KEY(object_id)
REFERENCES ERObject (object_id));


CREATE TABLE Relationship_Entitiy
(relationship_id NUMBER(10),
entity_id NUMBER(10),
EtoMany NUMBER(1),
CONSTRAINT “ENTITY_RELATIONSHIP_REL_FK” FOREIGN KEY(relationship_id)
REFERENCES RELATIONSHIP (relationship_id),
CONSTRAINT “ENTITY_RELATIONSHIP_ENT_FK” FOREIGN KEY(entity_id)
REFERENCES ENTITY (entity_id));




CREATE SEQUENCE SCHEMA_KEY
START WITH 1
INCREMENT BY 1
MAXVALUE 1000
CYCLE NOCACHE;

CREATE SEQUENCE EROBJECT_KEY
START WITH 1
INCREMENT BY 1
MAXVALUE 1000
CYCLE NOCACHE;

CREATE SEQUENCE ENTITY_KEY
START WITH 1
INCREMENT BY 1
MAXVALUE 1000
CYCLE NOCACHE;

CREATE SEQUENCE ATTRIBUTE_KEY
START WITH 1
INCREMENT BY 1
MAXVALUE 1000d NUMBER(10),
CYCLE NOCACHE;

CREATE SEQUENCE RELATIONSHIP_KEY
START WITH 1
INCREMENT BY 1
MAXVALUE 1000
CYCLE NOCACHE;